const DECREMENT = "DECREMENT";
const TWODECREMENT = "TWODECREMENT";
const INCREMENT = "INCREMENT";
const TWOINCREMENT = "TWOINCREMENT";
const SQUARE = "SQUARE";
const RESET = "RESET";

export {DECREMENT,TWODECREMENT,INCREMENT,TWOINCREMENT,SQUARE,RESET}